# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rviz_cloud_annotation/UndoRedoState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class UndoRedoState(genpy.Message):
  _md5sum = "43c106a96c078080d8c117fdd425c0a0"
  _type = "rviz_cloud_annotation/UndoRedoState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool redo_enabled
string redo_description

bool undo_enabled
string undo_description
"""
  __slots__ = ['redo_enabled','redo_description','undo_enabled','undo_description']
  _slot_types = ['bool','string','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       redo_enabled,redo_description,undo_enabled,undo_description

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UndoRedoState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.redo_enabled is None:
        self.redo_enabled = False
      if self.redo_description is None:
        self.redo_description = ''
      if self.undo_enabled is None:
        self.undo_enabled = False
      if self.undo_description is None:
        self.undo_description = ''
    else:
      self.redo_enabled = False
      self.redo_description = ''
      self.undo_enabled = False
      self.undo_description = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.redo_enabled))
      _x = self.redo_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.undo_enabled))
      _x = self.undo_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.redo_enabled,) = _get_struct_B().unpack(str[start:end])
      self.redo_enabled = bool(self.redo_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.redo_description = str[start:end].decode('utf-8')
      else:
        self.redo_description = str[start:end]
      start = end
      end += 1
      (self.undo_enabled,) = _get_struct_B().unpack(str[start:end])
      self.undo_enabled = bool(self.undo_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.undo_description = str[start:end].decode('utf-8')
      else:
        self.undo_description = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.redo_enabled))
      _x = self.redo_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.undo_enabled))
      _x = self.undo_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.redo_enabled,) = _get_struct_B().unpack(str[start:end])
      self.redo_enabled = bool(self.redo_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.redo_description = str[start:end].decode('utf-8')
      else:
        self.redo_description = str[start:end]
      start = end
      end += 1
      (self.undo_enabled,) = _get_struct_B().unpack(str[start:end])
      self.undo_enabled = bool(self.undo_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.undo_description = str[start:end].decode('utf-8')
      else:
        self.undo_description = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
